name: React

#on:
  #push:
   # branches: [ master ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v3
       - name: build
         run: yarn install && yarn build
       - uses: actions/upload-artifact@master
         with:
           name: build artifacts
           path: build/

  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: configure aws
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - uses: actions/download-artifact@master
      with:
        name: build artifacts
        path: build
        
    - name: deploy to s3
      run: aws s3 sync ./build s3://${{ secrets.AWS_BUCKET_NAME }} --delete # overrite everything from source to target
      
